services:
  greenlight:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
